USE [IMScertificate_Dev];
SET NOCOUNT ON;

DECLARE @HasIdentity bit =
(
    SELECT CASE WHEN EXISTS (
        SELECT 1
        FROM sys.columns
        WHERE [object_id] = OBJECT_ID(N'[IMScertificate_Dev].[dbo].[tblTranslationOrigin]')
          AND [name] = N'TranslationOriginId'
          AND is_identity = 1
    ) THEN 1 ELSE 0 END
);

DECLARE @Src TABLE
(
    TranslationOriginId int,
    TranslationOrigin nvarchar(1000),
    German nvarchar(1000),
    French nvarchar(1000),
    Italian nvarchar(1000),
    Japanese nvarchar(1000),
    Korean nvarchar(1000),
    ChineseSimplified nvarchar(1000),
    ChineseTraditional nvarchar(1000)
);


INSERT INTO @Src (TranslationOriginId, TranslationOrigin, German, French, Italian, Japanese, Korean, ChineseSimplified, ChineseTraditional) VALUES
(133, N'Software Type (1)', N'Softwaretyp (1)', N'Type de logiciel (1)', N'Tipo di software (1)', N'ソフトウェアの種類 (1)', N'소프트웨어 유형 (1)', N'软件类型 (1)', N'軟體類型 (1)'),
(134, N'Gauge Type (1)', N'Messgerätetyp (1)', N'Type de jauge (1)', N'Tipo di tastatore (1)', N'ゲージ種類 (1)', N'게이지 유형 (1)', N'量规类型 (1)', N'量規類型 (1)'),
(135, N'Calibration Ball', N'Kalibrierkugel', N'Bille d''étalonnage', N'Sfera di calibrazione', N'校正球', N'교정 볼', N'校准球', N'校準球'),
(136, N'Performed at 2mm/s using a 60mm Diamond Stylus, Assumes a calibration artefact of perfect radius.',
      N'Durchgeführt mit 60 mm Diamant-Taster bei 2 mm/s; Kalibrierkörper mit perfektem Radius angenommen.',
      N'Réalisé à 2 mm/s avec un stylet diamant de 60 mm; suppose un artefact d’étalonnage de rayon parfait.',
      N'Eseguito a 2 mm/s utilizzando uno stilo diamantato da 60 mm; si assume un artefatto di calibrazione a raggio perfetto.',
      N'60mmダイヤモンドスタイラスを用い2mm/sで実施。校正用アーティファクトは完全な半径であると仮定。',
      N'60mm 다이아몬드 스타일러스를 사용하여 2mm/s로 수행. 교정 아티팩트가 완전한 반지름이라고 가정.',
      N'使用60 mm金刚石触针以2 mm/s执行；假设校准件具有完美半径。',
      N'使用60 mm金剛石觸針以2 mm/s執行；假設校準件具有完美半徑。'),
(137, N'Pt', N'Pt', N'Pt', N'Pt', N'Pt', N'Pt', N'Pt', N'Pt'),
(138, N'Primary, LS Arc Ls 0.25mm',
      N'Primär, LS Arc Ls 0,25 mm',
      N'Primaire, LS Arc Ls 0,25 mm',
      N'Primario, LS Arc Ls 0,25 mm',
      N'一次，LS Arc Ls 0.25mm',
      N'1차, LS Arc Ls 0.25mm',
      N'一次，LS Arc Ls 0.25 mm',
      N'一次，LS Arc Ls 0.25 mm'),
(139, N'Gauge Calibration- Ball (Std) - Pt',
      N'Messgerät-Kalibrierung - Kugel (Std) - Pt',
      N'Étalonnage jauge - Bille (Std) - Pt',
      N'Calibrazione gauge - Sfera (Std) - Pt',
      N'ゲージ校正 - 球（Std）- Pt',
      N'게이지 교정 - 볼(표준) - Pt',
      N'量规校准 - 球（标准）- Pt',
      N'量規校準 - 球（標準）- Pt'),
(140, N'Gauge Range (1)',
      N'Messbereich (1)',
      N'Plage de jauge (1)',
      N'Campo della sonda (1)',
      N'ゲージレンジ (1)',
      N'게이지 범위 (1)',
      N'量规量程 (1)',
      N'量規量程 (1)'),
(141, N'Using a 160mm Stylus',
      N'Verwendung eines 160 mm-Tasters',
      N'Utilisation d’un stylet de 160 mm',
      N'Utilizzando uno stilo da 160 mm',
      N'160mmスタイラスを使用',
      N'160mm 스타일러스 사용',
      N'使用160 mm触针',
      N'使用160 mm觸針'),
(142, N'Gauge Calibration- Ball (WRi) - Pt',
      N'Messgerät-Kalibrierung - Kugel (WRi) - Pt',
      N'Étalonnage jauge - Bille (WRi) - Pt',
      N'Calibrazione gauge - Sfera (WRi) - Pt',
      N'ゲージ校正 - 球（WRi）- Pt',
      N'게이지 교정 - 볼(WRi) - Pt',
      N'量规校准 - 球（WRi）- Pt',
      N'量規校準 - 球（WRi）- Pt'),
(143, N'Performed at 2mm/s using a 160mm Stylus, Assumes a calibration artefact of perfect radius.',
      N'Durchgeführt mit 160 mm Taster bei 2 mm/s; Kalibrierkörper mit perfektem Radius angenommen.',
      N'Réalisé à 2 mm/s avec un stylet de 160 mm; suppose un artefact d’étalonnage de rayon parfait.',
      N'Eseguito a 2 mm/s con stilo da 160 mm; si assume un artefatto di calibrazione a raggio perfetto.',
      N'160mmスタイラスを用い2mm/sで実施。校正用アーティファクトは完全な半径と仮定。',
      N'160mm 스타일러스를 사용하여 2mm/s로 수행. 교정 아티팩트가 완전한 반지름이라고 가정.',
      N'使用160 mm触针以2 mm/s执行；假设校准件具有完美半径。',
      N'使用160 mm觸針以2 mm/s執行；假設校準件具有完美半徑。'),
(144, N'PAT Equipment',
      N'PAT-Geräte',
      N'Équipement PAT',
      N'Apparecchiatura PAT',
      N'PAT 装置',
      N'PAT 장비',
      N'PAT 设备',
      N'PAT 設備'),
(145, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(146, N'Earth Resistance, Current Leakage, Insulation',
      N'Erdungswiderstand, Ableitstrom, Isolierung',
      N'Résistance de terre, courant de fuite, isolation',
      N'Resistenza di terra, corrente di dispersione, isolamento',
      N'接地抵抗、漏れ電流、絶縁',
      N'접지 저항, 누설 전류, 절연',
      N'接地电阻、漏电流、绝缘',
      N'接地電阻、漏電流、絕緣'),
(147, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(148, N'Pat Test',
      N'PAT-Prüfung',
      N'Test PAT',
      N'Prova PAT',
      N'PAT 試験',
      N'PAT 테스트',
      N'PAT 测试',
      N'PAT 測試'),
(149, N'Software and Hardware Joystick',
      N'Software- und Hardware-Joystick',
      N'Joystick logiciel et matériel',
      N'Joystick software e hardware',
      N'ソフトウェアおよびハードウェア ジョイスティック',
      N'소프트웨어 및 하드웨어 조이스틱',
      N'软件和硬件摇杆',
      N'軟體與硬體搖桿'),
(150, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(151, N'Movement of all Axis - Via Computer and Joystick Checked',
      N'Bewegung aller Achsen – über Computer und Joystick geprüft',
      N'Mouvement de tous les axes – vérifié via ordinateur et joystick',
      N'Movimento di tutti gli assi – verificato tramite computer e joystick',
      N'すべての軸の動作 - コンピュータとジョイスティックで確認',
      N'모든 축의 이동 - 컴퓨터와 조이스틱을 통해 점검',
      N'所有轴的运动——通过计算机和摇杆检查',
      N'所有軸的移動——透過電腦與搖桿檢查'),
(152, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(153, N'End-stops on all Axis - Checked',
      N'Endanschläge an allen Achsen – geprüft',
      N'Butées sur tous les axes – vérifiées',
      N'Finecorsa su tutti gli assi – verificati',
      N'全軸のエンドストップ - 確認済み',
      N'모든 축의 엔드스톱 - 점검 완료',
      N'所有轴的限位——已检查',
      N'所有軸的限位——已檢查'),
(154, N'GDC Software check',
      N'GDC Software-Prüfung',
      N'Vérification logicielle GDC',
      N'Controllo software GDC',
      N'GDC ソフトウェアチェック',
      N'GDC 소프트웨어 점검',
      N'GDC 软件检查',
      N'GDC 軟體檢查'),
(155, N'Pass/Fail',
      N'Bestanden/Nicht bestanden',
      N'Réussite/Échec',
      N'Superato/Non superato',
      N'合格/不合格',
      N'합격/불합격',
      N'通过/失败',
      N'通過/失敗'),
(156, N'Automatic IMS Check completed via GDC',
      N'Automatische IMS-Prüfung über GDC abgeschlossen',
      N'Contrôle IMS automatique terminé via GDC',
      N'Verifica IMS automatica completata tramite GDC',
      N'GDC を介した自動 IMS チェック完了',
      N'GDC를 통한 자동 IMS 점검 완료',
      N'通过 GDC 完成自动 IMS 检查',
      N'透過 GDC 完成自動 IMS 檢查'),
(157, N'Gauge FCG/VCG (1)',
      N'Messgerät FCG/VCG (1)',
      N'Jauge FCG/VCG (1)',
      N'Gauge FCG/VCG (1)',
      N'ゲージ FCG/VCG (1)',
      N'게이지 FCG/VCG (1)',
      N'量规 FCG/VCG (1)',
      N'量規 FCG/VCG (1)'),
(158, N'Gauge Lift Lower (1)',
      N'Messgerät Heben/Senken (1)',
      N'Levage/Abaissement de la jauge (1)',
      N'Sollevamento/abbassamento gauge (1)',
      N'ゲージ昇降 (1)',
      N'게이지 상승/하강 (1)',
      N'量规升降 (1)',
      N'量規升降 (1)'),
(159, N'Gauge Bias (1)',
      N'Messgerät-Bias (1)',
      N'Biais de jauge (1)',
      N'Bias della gauge (1)',
      N'ゲージバイアス (1)',
      N'게이지 바이어스 (1)',
      N'量规偏置 (1)',
      N'量規偏置 (1)'),
(160, N'Software Version (1)',
      N'Softwareversion (1)',
      N'Version du logiciel (1)',
      N'Versione software (1)',
      N'ソフトウェア バージョン (1)',
      N'소프트웨어 버전 (1)',
      N'软件版本 (1)',
      N'軟體版本 (1)'),
(161, N'Software Level (1)',
      N'Softwarestand (1)',
      N'Niveau logiciel (1)',
      N'Livello software (1)',
      N'ソフトウェア レベル (1)',
      N'소프트웨어 레벨 (1)',
      N'软件级别 (1)',
      N'軟體等級 (1)'),
(162, N'Software Type (2)',
      N'Softwaretyp (2)',
      N'Type de logiciel (2)',
      N'Tipo di software (2)',
      N'ソフトウェアの種類 (2)',
      N'소프트웨어 유형 (2)',
      N'软件类型 (2)',
      N'軟體類型 (2)'),
(163, N'Software Version (2)',
      N'Softwareversion (2)',
      N'Version du logiciel (2)',
      N'Versione software (2)',
      N'ソフトウェア バージョン (2)',
      N'소프트웨어 버전 (2)',
      N'软件版本 (2)',
      N'軟體版本 (2)'),
(164, N'Software Level (2)',
      N'Softwarestand (2)',
      N'Niveau logiciel (2)',
      N'Livello software (2)',
      N'ソフトウェア レベル (2)',
      N'소프트웨어 레벨 (2)',
      N'软件级别 (2)',
      N'軟體等級 (2)'),
(165, N'Harmonics',
      N'Harmonische',
      N'Harmoniques',
      N'Armoniche',
      N'高調波',
      N'고조파',
      N'谐波',
      N'諧波'),
(166, N'Contour',
      N'Kontur',
      N'Contour',
      N'Contorno',
      N'輪郭',
      N'윤곽',
      N'轮廓',
      N'輪廓'),
(167, N'Surface Finish Vertical - Roundness',
      N'Oberflächenrauheit Vertikal – Rundheit',
      N'Finition de surface verticale - Rondeur',
      N'Finitura superficiale verticale - Rondezza',
      N'表面粗さ（垂直）- 真円度',
      N'표면 조도 수직 - 원형도',
      N'表面粗糙度 垂直 - 圆度',
      N'表面粗糙度 垂直 - 圓度'),
(168, N'Surface Finish Horizontal - Roundness',
      N'Oberflächenrauheit Horizontal – Rundheit',
      N'Finition de surface horizontale - Rondeur',
      N'Finitura superficiale orizzontale - Rondezza',
      N'表面粗さ（水平）- 真円度',
      N'표면 조도 수평 - 원형도',
      N'表面粗糙度 水平 - 圆度',
      N'表面粗糙度 水平 - 圓度'),
(169, N'Surface Finish Radial - Roundness',
      N'Oberflächenrauheit Radial – Rundheit',
      N'Finition de surface radiale - Rondeur',
      N'Finitura superficiale radiale - Rondezza',
      N'表面粗さ（半径方向）- 真円度',
      N'표면 조도 반경 방향 - 원형도',
      N'表面粗糙度 径向 - 圆度',
      N'表面粗糙度 徑向 - 圓度'),
(170, N'Surface Finish Axial - Roundness',
      N'Oberflächenrauheit Axial – Rundheit',
      N'Finition de surface axiale - Rondeur',
      N'Finitura superficiale assiale - Rondezza',
      N'表面粗さ（軸方向）- 真円度',
      N'표면 조도 축방향 - 원형도',
      N'表面粗糙度 轴向 - 圆度',
      N'表面粗糙度 軸向 - 圓度'),
(171, N'Gauge Type (2)',
      N'Messgerätetyp (2)',
      N'Type de jauge (2)',
      N'Tipo di tastatore (2)',
      N'ゲージ種類 (2)',
      N'게이지 유형 (2)',
      N'量规类型 (2)',
      N'量規類型 (2)'),
(172, N'Gauge Range (2)',
      N'Messbereich (2)',
      N'Plage de jauge (2)',
      N'Campo della sonda (2)',
      N'ゲージレンジ (2)',
      N'게이지 범위 (2)',
      N'量规量程 (2)',
      N'量規量程 (2)'),
(173, N'Gauge FCG/VCG (2)',
      N'Messgerät FCG/VCG (2)',
      N'Jauge FCG/VCG (2)',
      N'Gauge FCG/VCG (2)',
      N'ゲージ FCG/VCG (2)',
      N'게이지 FCG/VCG (2)',
      N'量规 FCG/VCG (2)',
      N'量規 FCG/VCG (2)'),
(174, N'Gauge Lift Lower (2)',
      N'Messgerät Heben/Senken (2)',
      N'Levage/Abaissement de la jauge (2)',
      N'Sollevamento/abbassamento gauge (2)',
      N'ゲージ昇降 (2)',
      N'게이지 상승/하강 (2)',
      N'量规升降 (2)',
      N'量規升降 (2)'),
(175, N'Gauge Bias (2)',
      N'Messgerät-Bias (2)',
      N'Biais de jauge (2)',
      N'Bias della gauge (2)',
      N'ゲージバイアス (2)',
      N'게이지 바이어스 (2)',
      N'量规偏置 (2)',
      N'量規偏置 (2)'),
(176, N'Arm Type',
      N'Armtyp',
      N'Type de bras',
      N'Tipo di braccio',
      N'アームタイプ',
      N'암 타입',
      N'臂类型',
      N'臂類型'),
(177, N'Arm Length',
      N'Armlänge',
      N'Longueur du bras',
      N'Lunghezza braccio',
      N'アーム長',
      N'암 길이',
      N'臂长',
      N'臂長'),
(178, N'Column Type',
      N'Säulentyp',
      N'Type de colonne',
      N'Tipo di colonna',
      N'コラムタイプ',
      N'컬럼 유형',
      N'立柱类型',
      N'立柱類型'),
(179, N'Column Length',
      N'Säulenlänge',
      N'Longueur de colonne',
      N'Lunghezza colonna',
      N'コラム長',
      N'컬럼 길이',
      N'立柱长度',
      N'立柱長度'),
(180, N'Pass / Fail',
      N'Bestanden / Nicht bestanden',
      N'Réussite / Échec',
      N'Superato / Non superato',
      N'合格 / 不合格',
      N'합격 / 불합격',
      N'通过 / 失败',
      N'通過 / 失敗'),
(181, N'Earth Resistance, Current Leakage, Insulation',
      N'Erdungswiderstand, Ableitstrom, Isolierung',
      N'Résistance de terre, courant de fuite, isolation',
      N'Resistenza di terra, corrente di dispersione, isolamento',
      N'接地抵抗、漏れ電流、絶縁',
      N'접지 저항, 누설 전류, 절연',
      N'接地电阻、漏电流、绝缘',
      N'接地電阻、漏電流、絕緣'),
(182, N'Ball Radius Measurement (Std) - Pt',
      N'Kugelradius-Messung (Std) - Pt',
      N'Mesure du rayon de bille (Std) - Pt',
      N'Misura raggio sfera (Std) - Pt',
      N'球半径測定（Std）- Pt',
      N'볼 반경 측정(표준) - Pt',
      N'球半径测量（标准）- Pt',
      N'球半徑測量（標準）- Pt');

IF @HasIdentity = 1 SET IDENTITY_INSERT [IMScertificate_Dev].[dbo].[tblTranslationOrigin] ON;

MERGE [IMScertificate_Dev].[dbo].[tblTranslationOrigin] AS tgt
USING @Src AS s
   ON tgt.TranslationOriginId = s.TranslationOriginId
WHEN MATCHED THEN
    UPDATE SET
        tgt.TranslationOrigin  = s.TranslationOrigin,
        tgt.German             = s.German,
        tgt.French             = s.French,
        tgt.Italian            = s.Italian,
        tgt.Japanese           = s.Japanese,
        tgt.Korean             = s.Korean,
        tgt.ChineseSimplified  = s.ChineseSimplified,
        tgt.ChineseTraditional = s.ChineseTraditional
WHEN NOT MATCHED BY TARGET THEN
    INSERT (TranslationOriginId, TranslationOrigin, German, French, Italian, Japanese, Korean, ChineseSimplified, ChineseTraditional)
    VALUES (s.TranslationOriginId, s.TranslationOrigin, s.German, s.French, s.Italian, s.Japanese, s.Korean, s.ChineseSimplified, s.ChineseTraditional);

IF @HasIdentity = 1 SET IDENTITY_INSERT [IMScertificate_Dev].[dbo].[tblTranslationOrigin] OFF;
